### ISSUE TITLE
urgent

### ISSUE THREAD

**Issue by hhh12345678990** [ultravideo/Open3DGen#13]
no enough landmarks in view ：0
 what is the reason

**Comment by teo3n** [comment]
Please, for future reference use the bug reporting best practices that can be found e.g. here: [https://github.com/brycelelbach/cpp_bug_reporting_guidelines](https://github.com/brycelelbach/cpp_bug_reporting_guidelines).
With the given information the problem could be almost anything, although my educated guess would be either really bad quality video or too fast movements, or both.

**Comment by hhh12345678990** [comment]
![image](https://github.com/ultravideo/Open3DGen/assets/56677956/ba524e94-3eef-4277-bd07-78669fde949b)

**Comment by hhh12345678990** [comment]
![image](https://github.com/ultravideo/Open3DGen/assets/56677956/6ff11ba8-266b-413d-8368-31f0d3ec5b2d)

**Comment by hhh12345678990** [comment]
![image](https://github.com/ultravideo/Open3DGen/assets/56677956/516bf6d6-bb87-43c8-a26b-30ddb1ea5b50)

**Comment by hhh12345678990** [comment]
error like this

**Comment by hhh12345678990** [comment]
> 为了将来参考，请使用错误报告最佳实践，可以在这里找到： https: [//github.com/brycelelbach/cpp_bug_reporting_guidelines](https://github.com/brycelelbach/cpp_bug_reporting_guidelines)。 根据给定的信息，问题几乎可能是任何问题，尽管我有根据的猜测可能是视频质量非常差或动作太快，或两者兼而有之。

我觉得我生成的数据质量还行

**Comment by teo3n** [comment]
All of the processing parameters you can tune are in `src/constants.h`, but unless you can change your input data then that's about it. I also noticed you have set the max number of features to only 100, I'd recommend at least 1000 if not even more. I'd also recommend setting `reject_blur` to 0.
