### ISSUE TITLE
question about win10 platform

### ISSUE THREAD

**Issue by MZener** [ultravideo/Open3DGen#2]
thanks for your sharing.  Can this code run on win10？ I try to compile it, but a lot of errors occurred, what's the version number of the reference library you use? Could you give me some advice about how to run on win10. thanks a lot. here is my results: 
vs2019 
gtsam3.2.3 
boost1.5.9 
open3d0.14.1
![微信截图_20220103221236](https://user-images.githubusercontent.com/38679014/147940613-50c12cfb-021a-40f5-a3bf-3405b4a3db7d.png)

**Comment by teo3n** [comment]
Unfortunately I do not understand Chinese, so I can only guess what's wrong here. To me it looks like a problem with the C++ standard library and not the libraries used. The library versions also look correct to me. 
Please note, Open3DGen has never before been tested on Windows and on, I assume, MSVC. For reference, Clang and GCC work fine on Linux.

**Comment by MZener** [comment]
thanks a lot
